### ISSUE TITLE
Occasional NullPointerException crash on signin attempt

### ISSUE THREAD

**Issue by Tw1ddle** [SempaiGames/extension-googleplaygames#10]
Occasionally our app crashes when trying to login (once) after launching the app. I'm seeing this on an Xperia Z3, Android 5.0.2, with ```openfl-gpg 1.3.0``` and ```openfl-gps-lib 1.0.4``` from haxelib.

```
GooglePlayGames.init(false);
 // Load some other stuff...
 GooglePlayGames.login();
``` 

Seeing the following logcat output:

```
D/GameHelper(  587): GameHelper: Debug log enabled.
D/GameHelper(  587): GameHelper: Setup: requested clients: 1
I/OPENFL-GPG(  587): PlayGames: Forcing Login
W/PopupManager(  587): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
D/AndroidRuntime(  587): Shutting down VM
W/System.err(  587): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.gpgex.GameHelper.setMaxAutoSignInAttempts(int)' on a null object reference
W/System.err(  587):    at com.gpgex.GooglePlayGames$1.run(GooglePlayGames.java:55)
W/System.err(  587):    at android.os.Handler.handleCallback(Handler.java:739)
W/System.err(  587):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(  587):    at android.os.Looper.loop(Looper.java:211)
W/System.err(  587):    at android.app.ActivityThread.main(ActivityThread.java:5321)
W/System.err(  587):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(  587):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(  587):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
W/System.err(  587):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
E/AndroidRuntime(  587): FATAL EXCEPTION: main
E/AndroidRuntime(  587): Process: uk.co.joecreates.werewolftycoon, PID: 587
E/AndroidRuntime(  587): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.gpgex.GameHelper.setMaxAutoSignInAttempts(int)' on a null object reference
E/AndroidRuntime(  587):        at com.gpgex.GooglePlayGames$1.run(GooglePlayGames.java:55)
E/AndroidRuntime(  587):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(  587):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(  587):        at android.os.Looper.loop(Looper.java:211)
E/AndroidRuntime(  587):        at android.app.ActivityThread.main(ActivityThread.java:5321)
E/AndroidRuntime(  587):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  587):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(  587):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
E/AndroidRuntime(  587):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
D/ActivityManager(  831): New dropbox entry: uk.co.joecreates.werewolftycoon, data_app_crash, 99dd08a4-aeaf-492a-9f71-e7d72542ec6c
W/ActivityManager(  831):   Force finishing activity uk.co.joecreates.werewolftycoon/.MainActivity
```

**Comment by fbricker** [comment]
Hi, we've published a new version of the extension yesterday. Can you update to that version (updating also your google-play-services library from Android Manager?
If the issue persists, you should try calling the Login a bit later instead of calling it on the same function where you call Init - you can simply do haxe.Timer.delay(GooglePlayGames.login,100); for this.

Please let me know if any of this solves your issues :)
